SOURCES/rpmbuilder

* Fixed bug with downloading local files which contains http/ftp/http in name

Version 1.0.4

---

SOURCES/rpmbuilder
readme.md
rpmbuilder.spec

* Feature added: package install before build

Version 1.0.6

---

SOURCES/rpmbuilder
readme.md
rpmbuilder.spec

* Fixed bug with parsing remote build definition
* Fixed build on CentOS 7

Version 1.0.7

---

SOURCES/rpmbuilder
rpmbuilder.spec

* Improved working with yum cache

Version 1.0.8

---

SOURCES/builder.sudoers
SOURCES/rpmbuilder
readme.md
rpmbuilder-node.spec
rpmbuilder.spec

* [`rpmbuilder`] `yum-builddep` usage implemented
* [`rpmbuilder-node`] Sudoers file updated for `yum-builddep` usage

Version 1.1.0

---

SOURCES/rpmbuilder
rpmbuilder.spec

* `-dl` without given path download files to current directory

Version 1.1.1

---

SOURCES/rpmbuilder
rpmbuilder.spec

* Fixed bug with disabling repository

Version 1.1.2

---

SOURCES/rpmbuilder
rpmbuilder-node.spec
rpmbuilder.spec

* Code refactoring
* Improved specs

Version 1.1.3

---

SOURCES/rpmbuilder
rpmbuilder.spec

* `RPMB-112` UI improvements
* `RPMB-111` Fixed typos in help output
* `RPMB-110` Fixed bug with processing `remote` argument

Version 1.1.4

---

SOURCES/rpmbuilder
rpmbuilder.spec

* `RPMB-110` Fixed bug with processing remote argument

Version 1.1.5

---

SOURCES/rpmbuilder
rpmbuilder.spec

* Fixed bug with packaging sources from SVN repository

Version 1.2.2

---

SOURCES/rpmbuilder
rpmbuilder.spec

* `RPMB-115` Added package validation after build

Version 1.3.0

---

SOURCES/rpmbuilder
rpmbuilder.spec

* `RPMB-122` Improved checking remote sources availability

Version 1.5.2

---

rpmbuilder-node.spec

* `RPMB-124` Enable password authentication by default

rpmbuilder-node improvements

---

SOURCES/buildmon
SOURCES/rpmbuilder
rpmbuilder-node.spec
rpmbuilder.spec

* `[rpmbuilder]` Fixed bug with handling errors during package validation
* `[rpmbuilder-node]` Fixed bug with removing lock file

Version 1.6.1

---

SOURCES/nodeinfo
SOURCES/rpmbuilder
SOURCES/rpmunbuilder
readme.md
rpmbuilder-node.spec
rpmbuilder.spec

* `[rpmbuilder-node]` Improved `nodeinfo` output
* `[rpmbuilder]` Improved help content
* `[rpmbuilder]` Improved error messages
* `[rpmbuilder]` Fixed bug with colors disabling
* `[rpmbuilder]` Fixed bug with changing permissions on local lock

Version 1.6.2

---

SOURCES/rpmbuilder
rpmbuilder.spec

Version 1.6.3

---

SOURCES/rpmbuilder
rpmbuilder.spec

* Fixed bug with using `--without` flag

Version 1.6.4

---

SOURCES/rpmbuilder
rpmbuilder.spec

* `[rpmbuilder]` Added error message if dependencies can't be installed
* `[rpmbuilder]` Improved UI
* `[rpmbuilder]` Some minor bugfixes

Version 1.7.0

---

SOURCES/rpmbuilder
SOURCES/rpmunbuilder
rpmbuilder.spec

* `RPMB-133` Output errors to stderr
* `RPMB-132` Fixed bug with wrong message about existing lock file
* `RPMB-132` Fixed bug with lack of removing lock file for local build in some cases

Version 1.7.1

---

SOURCES/rpmbuilder
rpmbuilder.spec

* Fixed bug with cleaning temporary data

Version 1.7.3

---

.github/CONTRIBUTING.md
.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md
SOURCES/rpmbuilder
rpmbuilder.spec

* Use custom user-agent
* Improved gopack support
* Improved getting sources from DVCS/VCS
* Full-size separator support
* `RPMB-136` Fixed bug with storing golang sources to defined directory
* `RPMB-137` Fixed bug with downloading golang sources even if file already exist

Version 1.8.0

---

SOURCES/rpmbuilder
readme.md
rpmbuilder.spec

* `[rpmbuilder]` Improved separator output in tmux
* `[rpmbuilder]` Improved help output

Version 1.8.1

---

SOURCES/rpmbuilder
rpmbuilder.spec

* Fixed compatibility with latest version of gopack

Version 1.8.2

---

SOURCES/rpmbuilder
readme.md
rpmbuilder.spec

Version 1.9.0

---

SOURCES/rpmbuilder
readme.md
rpmbuilder.spec

* `RPMB-139` Added option `--exclude-package`/`-EX` for excluding some packages from installation
* Improved working with spec properties

Version 1.10.0

---

SOURCES/rpmbuilder
rpmbuilder.spec

* Fixed compatibility with latest version of `gopack`

Version 1.10.1

---

README.md
SOURCES/rpmbuilder
SOURCES/rpmunbuilder
rpmbuilder.spec

* Updated argument parser
* Fixed bug in `rpmunbuilder` (thx to @gongled)

Version 2.2.1

---

README.md
SOURCES/libexec/build-local.shx
SOURCES/libexec/build-remote-worker.shx
SOURCES/libexec/build-remote.shx
SOURCES/libexec/build.shx
SOURCES/libexec/sources-remote.shx
SOURCES/libexec/sources-scm.shx
SOURCES/libexec/sources.shx
SOURCES/libexec/upload.shx
SOURCES/rpmbuilder
rpmbuilder.spec

* Added sources validation feature
* Minor UI improvements

Version 2.4.0

---

SECURITY.md
SOURCES/libexec/build.shx
SOURCES/rpmbuilder
rpmbuilder.spec

- Minor UI improvements
- Added checking options after reading inspec options

Version 2.4.2

---

README.md
SOURCES/libexec/build-local.shx
SOURCES/libexec/build-remote.shx
SOURCES/libexec/build.shx
SOURCES/libexec/package.shx
SOURCES/libexec/sources-remote.shx
SOURCES/libexec/sources-scm.shx
SOURCES/libexec/sources.shx
SOURCES/libexec/upload.shx
SOURCES/libexec/utils.shx
SOURCES/rpmbuilder
rpmbuilder.spec

* Automatic SHA-512 CRC generation feature
* Code refactoring

Version 2.5.0

---

README.md
SOURCES/rpmbuilder
SOURCES/rpmunbuilder
rpmbuilder.spec

* Removed handler for script errors

Version 2.5.2

---

README.md
SOURCES/libexec/build-local.shx
SOURCES/libexec/build-remote.shx
SOURCES/libexec/sources-golang.shx
SOURCES/libexec/spec.shx
SOURCES/rpmbuilder
SOURCES/rpmunbuilder
rpmbuilder.spec

- Updated options parser to the latest version
- Improved preferences parser
- Refactoring

Version 2.7.0

---

SOURCES/libexec/build-local.shx
SOURCES/libexec/build-remote.shx
SOURCES/libexec/build.shx
SOURCES/libexec/observer.shx
SOURCES/libexec/utils.shx
SOURCES/rpmbuilder
rpmbuilder.spec

- Improved UI
- Code refactoring

Version 2.11.0

---

.github/dependabot.yml
.github/workflows/ci.yml
README.md

* Improved CI workflow
* Added dependabot configuration
* Improved README

Maintenance improvements

---

SOURCES/libexec/observer.shx
SOURCES/rpmbuilder
rpmbuilder.spec

- Code refactoring
- Fixed UI bugs

Version 2.12.2

---

.docker/centos7.docker
.docker/node-centos7.docker
.docker/node-ol7.docker
.docker/node-ol8.docker
.docker/node-ol9.docker
.docker/ol7.docker
.docker/ol8.docker
.docker/ol9.docker
SOURCES/libexec/build-local.shx
SOURCES/libexec/sources.shx
SOURCES/nodeinfo
SOURCES/rpmbuilder
rpmbuilder.spec

* Improved container engine check in `nodeinfo`
* Minor UI improvements
* Images refactoring
* `gosu` updated to 1.16
- Fixed bug with local build due to lack of `upload.shx` file

Version 3.0.1

---

SOURCES/nodeinfo
rpmbuilder-node.spec

* Fixed bug with printing container info in `nodeinfo`

Fix bug with printing container info in nodeinfo

---

.github/workflows/ci.yml
.typos.toml
SOURCES/libexec/build-remote.shx
SOURCES/libexec/build.shx
SOURCES/libexec/package.shx
SOURCES/libexec/spec.shx
SOURCES/rpmbuilder
SOURCES/rpmunbuilder
rpmbuilder.spec

* Fixed bug with parsing in-spec variables with asterisk symbols
* Typos fixed

Version 3.0.2

---

.docker/centos7.docker
.docker/entrypoint
.docker/node-centos7.docker
.docker/node-ol7.docker
.docker/node-ol8.docker
.docker/node-ol9.docker
.docker/ol7.docker
.docker/ol8.docker
.docker/ol9.docker
README.md
SOURCES/rpmbuilder
rpmbuilder.spec

* Improved docker images
* Improved version output

Version 3.0.3

---

SOURCES/libexec/build-remote.shx
SOURCES/rpmbuilder
rpmbuilder.spec

* Added connection caching feature 🔥

Version 3.1.0

---

README.md
SOURCES/libexec/build-remote.shx
SOURCES/libexec/sources.shx
SOURCES/rpmbuilder
rpmbuilder.spec

- Fixed output of dependencies versions in version info
- Fixed usage examples

Version 3.1.1

---

.docker/centos7.docker
.docker/ol7.docker
.docker/ol8.docker
.docker/ol9.docker
.github/workflows/ci.yml
Makefile
README.md
SOURCES/libexec/build-local.shx
SOURCES/libexec/build-remote.shx
SOURCES/libexec/build.shx
SOURCES/libexec/sources-scm.shx
SOURCES/rpmbuilder
rpmbuilder-farm
rpmbuilder.spec

- Added script `rpmbuilder-farm` for bootstrapping `rpmbuilder` farm with Docker
- Option `-k`/`--key` now accepts base64 encoded data with private key
- Option `-r`/`--remote` can now be passed multiple times
- Added private key validation
- Added `tmux` check for parallel build
- Improved `-r`/`--remote` option validation
- Improved version info output
- Run `tmux` with UTF-8 support
- Code refactoring
- `gosu` updated to 1.17 in Dockerfiles
- Fixed bug with useless build host info parsing on multibuild
- Fixed bug with cleaning temporary data on multibuild
- Fixed bug with rendering help content when using Docker

Version 3.3.0

---

.docker/node-entrypoint
Makefile
SOURCES/rpmbuilder
rpmbuilder-farm
rpmbuilder.spec

* Improved images update in `rpmbuilder-farm`
* Code refactoring

Version 3.3.1

---

rpmbuilder-farm

- Improved version info
- Fixed bug with starting/stopping dead containers
- Fixed help output

Farm script fixes

---

SOURCES/libexec/build.shx
SOURCES/libexec/spec.shx
SOURCES/rpmbuilder
rpmbuilder.spec

Version 3.4.1

---

SOURCES/rpmbuilder
SOURCES/rpmunbuilder
rpmbuilder.spec

- Improved options parsing
- Code refactoring

Version 3.4.2

---

.docker/entrypoint
SOURCES/libexec/build-remote.shx
SOURCES/rpmbuilder
rpmbuilder.spec

- Improved support of `rpmbuild` on EL10

Version 3.4.4
